WITH HISTORY AS (
    SELECT 
        H.*,
        (END_DATE - START_DATE + 1) AS DIFF,
        CASE 
            WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
            WHEN (END_DATE - START_DATE + 1) >= 30 THEN '30일 이상'
            WHEN (END_DATE - START_DATE + 1) >= 7 THEN '7일 이상'
            ELSE '0'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
)
SELECT 
    H.HISTORY_ID,
    FLOOR(
        C.DAILY_FEE * 
        (CASE 
            WHEN H.DURATION_TYPE = '0' THEN 1
            ELSE (100 - NVL(D.DISCOUNT_RATE, 0)) * 0.01
         END) * H.DIFF
    ) AS FEE
FROM HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON H.DURATION_TYPE = D.DURATION_TYPE AND C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;