/* 없는 시간대는 출력이 안됨
SELECT
    CASE 
        WHEN HOUR(DATETIME) = 0 THEN 0
        WHEN HOUR(DATETIME) = 1 THEN 1
        WHEN HOUR(DATETIME) = 2 THEN 2
        WHEN HOUR(DATETIME) = 3 THEN 3
        WHEN HOUR(DATETIME) = 4 THEN 4
        WHEN HOUR(DATETIME) = 5 THEN 5
        WHEN HOUR(DATETIME) = 6 THEN 6
        WHEN HOUR(DATETIME) = 7 THEN 7
        WHEN HOUR(DATETIME) = 8 THEN 8
        WHEN HOUR(DATETIME) = 9 THEN 9
        WHEN HOUR(DATETIME) = 10 THEN 10
        WHEN HOUR(DATETIME) = 11 THEN 11
        WHEN HOUR(DATETIME) = 12 THEN 12
        WHEN HOUR(DATETIME) = 13 THEN 13
        WHEN HOUR(DATETIME) = 14 THEN 14
        WHEN HOUR(DATETIME) = 15 THEN 15
        WHEN HOUR(DATETIME) = 16 THEN 16
        WHEN HOUR(DATETIME) = 17 THEN 17
        WHEN HOUR(DATETIME) = 18 THEN 18
        WHEN HOUR(DATETIME) = 19 THEN 19
        WHEN HOUR(DATETIME) = 20 THEN 20
        WHEN HOUR(DATETIME) = 21 THEN 21
        WHEN HOUR(DATETIME) = 22 THEN 22
        WHEN HOUR(DATETIME) = 23 THEN 23
    END AS HOUR,
    COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
ORDER BY HOUR;
*/

-- MySQL = RECURSIVE, Oracle = CONNECT BY

WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)
SELECT
    h.HOUR,
    COALESCE(COUNT(a.DATETIME), 0) AS COUNT
FROM hours h
LEFT JOIN ANIMAL_OUTS a ON HOUR(a.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR;