-- ??
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE START_DATE BETWEEN TO_DATE('2022-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                      AND TO_DATE('2022-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
   AND (CAR_ID) IN 
        (SELECT CAR_ID 
           FROM (SELECT CAR_ID
                      , SUM(COUNT(*)) OVER (PARTITION BY CAR_ID ORDER BY CAR_ID 
                                             RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE START_DATE BETWEEN TO_DATE('2022-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
                                       AND TO_DATE('2022-10-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
                  GROUP BY CAR_ID HAVING COUNT(*) >= 5
                )
         )
 GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
 ORDER BY MONTH, CAR_ID DESC;