SELECT d.ID AS ID, d.EMAIL AS EMAIL, d.FIRST_NAME AS FIRST_NAME, d.LAST_NAME AS LAST_NAME
FROM DEVELOPERS d JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE = s.CODE
WHERE s.NAME IN('PYTHON', "C#")
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID