-- 오라클은 CONCAT대신 || 사용
SELECT CONCAT("/home/grep/src/", f.BOARD_ID, "/", f.FILE_ID, f.FILE_NAME, f.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f ON b.BOARD_ID=f.BOARD_ID
WHERE VIEWS IN (select max(VIEWS) from USED_GOODS_BOARD)
ORDER BY f.FILE_ID DESC;